geometry_msgs/Pose goal

uint8 Empty=0
uint8 LaneDriving=1
uint8 LaneDrivingWithSweeping=2
uint8 LaneDrivingWithRightBoundarySweeping=3
uint8 LaneDrivingWithLeftBoundarySweeping=4
uint8 CoverageSweeping=5
uint8 SearchingSweeping=6
uint8 BoundarySweeping=7
uint8 Parking=8
uint8 Reloading=9
uint8 DumpingTrash=10
uint8 ParkingMpc=11


uint8 lane_driving_sweeping_mode
uint8 free_space_sweeping_mode
int8 mission_order