Header header 
# ·ç»úËÙ¶È¿ØÖÆ [rpm] [0|0]
int32 FanSpeedCtrl 
#  [] [0|1]
int8 ShakerDusterCtrl 
# ÅçÎíœµ³Ÿ [] [0|1]
int8 DedustingCtrl 
# Ò»ŒüÇåÉš¿ØÖÆ [] [0|1]
int8 AutoCleaningStartCtrl 
# Ò»ŒüÇãµ¹ [] [0|1]
int8 AutoGarbageDumpStartCtrl 
# ÎüÅÌÉýœµ¿ØÖÆ [] [0|1]
int8 MouthpieceUpDownCtrl 
# ÉšÅÌÉýœµ [] [0|1]
int8 SweepPlateUpDown 
# ·ç»ú¹€×÷Ä£Êœ [] [0|1]
int8 FanModeCtrl 
# ·ç»úËÙ¶ÈÄ£Êœ [] [0|1]
int8 FanSpeedMode 
# ÉšÅÌ×ªËÙµ²Î»¿ØÖÆ [] [0|1]
int8 SweepModeCtrl 
# žî²Ý×ªËÙµ²Î»¿ØÖÆ [] [0|1]
int8 MowingSpeedCtrl 
#  [] [0|1]
bool BackUpSig 
